services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # BreadcrumbProvider Service
  Thormeier\BreadcrumbBundle\Provider\BreadcrumbProvider:
    public: true
    arguments:
      - '%thormeier_breadcrumb.class.model%'  # Inject parameter for model class
      - '%thormeier_breadcrumb.class.collection%'  # Inject parameter for collection class
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

  # BreadcrumbExtension Service
  Thormeier\BreadcrumbBundle\Twig\BreadcrumbExtension:
    arguments:
      - '@Thormeier\BreadcrumbBundle\Provider\BreadcrumbProvider'  # Inject breadcrumb provider service
      - '%thormeier_breadcrumb.template%'  # Inject template parameter
    tags:
      - { name: twig.extension }

  # Inner AttachBreadcrumbLoader Service
  Thormeier\BreadcrumbBundle\Routing\BreadcrumbAttachLoader:
    # No arguments needed for inner loader unless explicitly required
